### ISSUE TITLE
Clicking "Cancel" or "X" in any form results in a bringing the user back to host page

### ISSUE THREAD

**Issue by will-chan** [rancherio/ui#13]
Anytime you click Cancel or the "X" icon to close the form, you will always be brought back to the main host page, not the page you were originally at.

Steps:
1. Click on a container within a host to bring up the container view page.
2. Click on the edit button to bring up a form
3. Click "Cancel"
4. The UI will refresh to the main host page, not the container detail page.

**Comment by will-chan** [comment]
Actually, this also happens after you save a form as well.

**Comment by vincent99** [comment]
Fixed in #28 to go back to the previous route (if there was one) and released in [v0.8.0](/rancherio/ui/releases/tag/v0.8.0) today
