### ISSUE TITLE
Starting a container from hosts view results in a start icon being shown

### ISSUE THREAD

**Issue by will-chan** [rancherio/ui#14]
![image](https://cloud.githubusercontent.com/assets/10134676/5649952/72a6b382-9657-11e4-9852-402b4f8ded93.png)

When you attempt to start a container from the host view, the Start icon is shown again.  I assume the Stop and Delete icon are valid state transitions but why does the Start icon need to be there since you are starting it already?

**Comment by vincent99** [comment]
This is in the API.. `start` is listed as an action on instances that are in `state: 'starting'`

**Comment by ibuildthecloud** [comment]
It's a bug in cattle

**Comment by vincent99** [comment]
Fixed in rancherio/cattle#147
