### ISSUE TITLE
Add copy/paste button for Host register link

### ISSUE THREAD

**Issue by cjellick** [rancherio/ui#48]
When registering a new host, you need to copy and paste the registration URL from the browser to your terminal. Having a button in the UI for the copy functionality would be nice.

Currently, if you just double click the text to select it, you catch a newline character and pasting it in the terminal causes it to immediately execute. I'd rather have it pasted without the newline so that I can review it before hitting enter.

**Comment by hibooboo2** [comment]
+1

**Comment by vincent99** [comment]
Fixed in #76
