### ISSUE TITLE
Add timer to automatically logout

### ISSUE THREAD

**Issue by vincent99** [rancherio/ui#59]

**Comment by deniseschannon** [comment]
@vincent99 Is this in reference to when Access Control is not configured? 

When access control is configured, GitHub Authentication will log it out and require authentication again.

**Comment by vincent99** [comment]
This is for when it is configured.. Github auth is good for days, but the JWT (JSON Web Token) that authenticates the UI to the backend is good for 16 hours.  Once that's up you should get sent automatically back to the the login page to login again.

**Comment by deniseschannon** [comment]
Created in rancherio/rancher. https://github.com/rancherio/rancher/issues/255
