### ISSUE TITLE
Container host link doesnt work if you accessed the shell

### ISSUE THREAD

**Issue by cjellick** [rancherio/ui#91]
Steps to reproduce:
1. Start a container
2. Click on the container to go to its page
3. Click the execute shell button
4. close the execute shell dialog
5. click the ***< Container*** link in the top left.

Expected behavior:
Taken back to host page

Actual behavior:
Execute shell dialog opens back up

**Comment by deniseschannon** [comment]
Created in rancherio/rancher: https://github.com/rancherio/rancher/issues/242
