### ISSUE TITLE
Display machine create/bootstrap progress to user

### ISSUE THREAD

**Issue by cjellick** [rancherio/ui#95]
After today's release (**3/13**) the transitioningMessage will be updated as a machine progresses through creation and bootstrapping.
 
@vincent99 you mentioned that reflecting status of machines in the UI possibly already worked, but when I ran this locally, the UI did not update to reflect that status.

**Comment by deniseschannon** [comment]
In v0.12.0, I see the messages in the different stages. I am closing cause it works.

![screen shot 2015-03-18 at 1 21 34 pm](https://cloud.githubusercontent.com/assets/11410997/6718580/00cd67cc-cd72-11e4-81dc-c534412647d8.png)

![screen shot 2015-03-18 at 1 23 03 pm](https://cloud.githubusercontent.com/assets/11410997/6718583/0529a902-cd72-11e4-8e61-ea43312fa758.png)
